defaults:
  - base_config
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: sphere
    storage: null
    n_trials: 2
    n_jobs: 1

    search_space:
      train.epochs:
        type: int
        low: 1
        high: 3
        step: 1

network:
  transformer:
    depth: 3
    heads: 1
    dropout: 0.0
    attention_type: col
    dim_head: 64
    scale_dim_internal_col: 4.0
    scale_dim_internal_row: 4.0
  num_workers: 0
  embedding_size: 10
  internal_dimension_embed_continuous: 100
  dropout_embed_continuous: 0.0
  batch_size: 256
pretrain:
  aug:
    cutmix:
      lam: 0.1
    mixup:
      lam: 0.1
  task:
    contrastive:
      constrastive_type: simsiam
      projhead_style: different
      nce_temp: 0.5
      weight: 0.1
      dropout: 0.0
    denoising:
      weight_cross_entropy: 0.5
      weight_mse: 0.5
      scale_dim_internal_sepmlp: 5.0
      dropout: 0.0
  optimizer:
    learning_rate: 0.0001
    other_params: {}
  epochs: 2
train:
  internal_dimension_output_layer: 20
  mlpfory_dropout: 0.0
  epochs: 1
  optimizer:
    learning_rate: 0.0001
    other_params: {}
