network:
  num_workers: 0
  embedding_size: 20
  depth: 2
  heads: 1
  ff_dropout: .0
  attention_type: col
  learning_rate: 0.0001
  learning_rate_pretraining: 0.03
  internal_dimension_output_layer: 10
  internal_dimension_embed_continuous: 10
  dim_head: 64
  scale_dim_internal_col: 4
  scale_dim_internal_row: 4
pretrain:
  aug:
    cutmix:
      lam: 0.1
    mixup:
      lam: 0.1
  task:
    contrastive: null
    contrastive_sim:
      weight: 0.1
    denoising:
      weight_cross_entropy: 0.5
      weight_mse: 0.5
      scale_dim_internal_sepmlp: 5
