network:
  num_workers: 1
  embedding_size: 20
  depth: 1
  heads: 1
  ff_dropout: .0
  attention_type: col
  learning_rate: 0.001
  learning_rate_pretraining: 0.03
  internal_dimension_output_layer: 10
  internal_dimension_embed_continuous: 10
pretrain:
  aug:
    cutmix:
      lam: 0.1
    mixup:
      lam: 0.1
  task:
    contrastive: null
    contrastive_sim:
      weight: 0.1
    denoising:
      weight_cross_entropy: 0.5
      weight_mse: 0.5
