defaults:
  - base_config
network:
  embedding_size: 10
  depth: 3
  heads: 1
  ff_dropout: .0
  attention_type:  'col'
pretrain:
  aug:
    cutmix:
      noise_lambda: 0.1
  task:
    contrastive:
      lam: 0.1
      projhead_style: 'same'
      nce_temp: 0.5
    denoising:
      weight_cross_entropy: 0.5
      weight_mse:  0.1